name = "Hugo - Software Kit"
license = "MIT"
licenselink = "https://github.com/wwkeyboard/hugo-software-kit/blob/master/LICENSE.md"
description = "A theme for building software kits, they are similar to, but not exactly like blogs. Based off the Huge Classic theme by goodroot."
homepage = "https://github.com/wwkeyboard/hugo-software-kit"
tags = ["minimal", "software-kit", "simple", "clean", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Aaron Lee"
  homepage = "http://aaronosaur.us"

[original]
  name = "Kellen Evan Person"
  homepage = "https://goodroot.ca"
  repo = "https://github.com/goodroot/hugo-classic"
